export const temp_data = {
  kg_name:'좋은 유치원',
  user_name:'봉미선',
  type:'ad',                      //pr,tc,ad
  auth:true,
}

export const users = [
{id: 0, name: '김성현', contact:'01043376752'},
{id: 0, name: '가나다', contact:'01012345678'},
{id: 0, name: '라마바', contact:'01098765432'},
{id: 0, name: '사아자', contact:'01013579246'},
{id: 0, name: '치키챠', contact:'010345782345'},
{id: 0, name: '아이린', contact:'01010293847'},
]

export const kinger = [
  {id: 0, name: 'abc유치원', adrr:'답십리로 130'},
  {id: 0, name: '가나다유치원', adrr:'공릉로 232'},
  {id: 0, name: '이찌니산유치원', adrr:'광야로 123'},
  {id: 0, name: '이얼싼유치원', adrr:'답십리로 130'},
  {id: 0, name: '123유치원', adrr:'공릉로 232'},
  {id: 0, name: 'xyz유치원', adrr:'광야로 123'},
  {id: 0, name: 'abc유치원', adrr:'답십리로 130'},
  {id: 0, name: '가나다유치원', adrr:'공릉로 232'},
  {id: 0, name: '이찌니산유치원', adrr:'광야로 123'},
  {id: 0, name: '이얼싼유치원', adrr:'답십리로 130'},
  {id: 0, name: '123유치원', adrr:'공릉로 232'},
  {id: 0, name: 'xyz유치원', adrr:'광야로 123'},
  {id: 0, name: 'abc유치원', adrr:'답십리로 130'},
  {id: 0, name: '가나다유치원', adrr:'공릉로 232'},
  {id: 0, name: '이찌니산유치원', adrr:'광야로 123'},
  {id: 0, name: '이얼싼유치원', adrr:'답십리로 130'},
  {id: 0, name: '123유치원', adrr:'공릉로 232'},
  {id: 0, name: 'xyz유치원', adrr:'광야로 123'},
  ]
  

export const btns_for_pr = [
{id: 0, title: '공지 모아보기', img:'book-outline', onclick:'NoticeBoard'},
{id: 1, title: '개인 톡', img:'clipboard-outline', onclick:'Talk'},
{id: 2, title: '셔틀 위치 확인', img:'logo-youtube', onclick:'Shuttle'},
];

export const btns_for_ad = [
{id: 0, title: '회원 관리', img:'book-outline', onclick:'Management'},
{id: 1, title: '공지 모아보기', img:'mail-outline', onclick:'NoticeBoard'},
{id: 2, title: '개인 톡', img:'call-outline', onclick:'Talk'},
{id: 3, title: '반/학생 추가', img:'clipboard-outline', onclick:'ForAdmin'},
{id: 4, title: '셔틀 관리', img:'car-outline', onclick:'Shuttle'},
{id: 5, title: '전화번호부', img:'log-in-outline', onclick:'Contact'},
];

export const list_current = [
{time: new Date(2021, 8, 1, 14, 49, 5), title: '학부모 게시판', content:'wow'},
{time: new Date(2021, 8, 1, 14, 4, 5), title: '가정통신문 확인', content:'네 알려드렸습니다~~'},
{time: new Date(2021, 8, 1, 3, 4, 5), title: '학부모 게시판', content:'응애'},
{time: new Date(2021, 7, 28, 3, 4, 5), title: '가정통신문 확인', content:'0829 알려드립니다'},
{time: new Date(2021, 7, 27, 3, 4, 5), title: '비트코인 갤러리', content:'이더리움 클래식 수익 500% 인증'},
];

export const list_parent = [
{time: new Date(2021, 8, 1, 14, 49, 5), title: 'wow', content:'Im addicted, 끊임없이 \n말을 걸어주는 나의 에스파 \n이런 교감, 너의 존잰 날 \n다른 차원으로 이끌었지 (oh) \n\n난 세상 중심에 \nYou re in the flat \n내 모든 action \n어린 너의 힘을 키워'},
{time: new Date(2021, 8, 1, 14, 4, 5), title: '네 알려드렸습니다~~', content:'넌 언젠가부터 Synk out \n노이즈같이 보여 \n더 이상 못 찾겠어 \n널 유혹해 삼킨 건, black mamba'},
{time: new Date(2021, 8, 1, 3, 4, 5), title: '응애', content:'Im on the next level yeah \n절대적 룰을 지켜 \n내 손을 놓지 말아 \n결속은 나의 무기 \n광야로 걸어가 \n알아 네 home ground \n위협에 맞서서 \n제껴라 제껴라 제껴라'},
{time: new Date(2021, 7, 28, 3, 4, 5), title: '0829 알려드립니다', content:'상상도 못한 black out \n유혹은 깊고 진해 \n(Too hot too hot) (Ooh ooh wee) \n맞잡은 손을 놓쳐 \n난 절대 포기 못해'},
{time: new Date(2021, 7, 27, 3, 4, 5), title: '룰루야 드가자!!', content:'Beat drop Naevis, calling \n절대로 뒤를 돌아보지 말아 \n광야의 것 탐내지 말아 \n약속이 깨지면 모두 걷잡을 수 없게 돼 \n언제부턴가 불안해져 가는 신호 \n널 파괴하고 말 거야 (we want it) \nCome on! Show me the way \nto Kosmo yeah yeah'}
];

export const list_notice = [
  {time: new Date(2021, 8, 1, 14, 49, 5), title: '0828 알려드립니다', content:'네 알려드렸습니다~~'},
  {time: new Date(2021, 8, 1, 14, 4, 5), title: '0829 알려드립니다', content:'네 알려드렸습니다~~'},
  {time: new Date(2021, 8, 1, 3, 4, 5), title: '0901 알려드립니다', content:'네 알려드렸습니다~~'},
  {time: new Date(2021, 7, 28, 3, 4, 5), title: '0902 알려드립니다', content:'네 알려드렸습니다~~'},
  {time: new Date(2021, 7, 27, 3, 4, 5), title: '0903 알려드립니다', content:'네 알려드렸습니다~~'},
  ];


export const comment =[
{time: new Date(2021, 8, 4, 14, 49, 5), nickname:'서연맘', content: 'ㅋㅋㅇㅈ',},
{time: new Date(2021, 8, 3, 14, 49, 5), nickname:'연서맘', content: 'ㄹㅇㅋㅋ2',},
{time: new Date(2021, 8, 2, 14, 49, 5), nickname:'주현맘', content: 'ㅋㅋㅇㅈ3',},
{time: new Date(2021, 8, 1, 14, 49, 5), nickname:'민준맘', content: 'ㅋㅋㅇㅈ4',},
{time: new Date(2021, 8, 1, 11, 49, 5), nickname:'경훈맘', content: 'ㅋㅋㅇㅈ5',},
]

export const classList = ['대한반','민국반','만세반','무궁반','백두반','한라반']
export const childList = ['aaa','ss','dd','ff','gg','hh','aaa','ss','dd','ff','gg','hh','aaa','ss','dd','ff','gg','hh','aaa','ss','dd','ff','gg','hh','aaa','ss','dd','ff','gg','hh']

export const area0 = [
  { label: '서울특별시', value: '서울특별시' },
  { label: '인천광역시', value: '인천광역시'  },
  { label: '대전광역시', value: '대전광역시' },
  { label: '광주광역시', value: '광주광역시'},
  { label: '대구광역시', value: '대구광역시'},
  { label: '울산광역시', value: '울산광역시'},
  { label: '부산광역시', value: '부산광역시'},
  { label: '경기도', value: '경기도'},
  { label: '강원도', value: '강원도'},
  { label: '충청북도', value: '충청북도'},
  { label: '충청남도', value: '충청남도'},
  { label: '전라북도', value: '전라북도'},
  { label: '전라남도', value: '전라남도'},
  { label: '경상북도', value: '경상북도'},
  { label: '경상남도', value: '경상남도'},
  { label: '제주도', value: '제주도'},
];

export const area1 = [
  { label: '강남구', value: '강남구', key:1 },
  { label: '강동구', value: '강동구', key:1 },
  { label: '강북구', value: '강북구', key:1 },
  { label: '강서구', value: '강서구', key:1 },
  { label: '관악구', value: '관악구', key:1 },
  { label: '광진구', value: '광진구', key:1 },
  { label: '구로구', value: '구로구', key:1 },
  { label: '금천구', value: '금천구', key:1 },
  { label: '노원구', value: '노원구', key:1 },
  { label: '도봉구', value: '도봉구', key:1 },
  { label: '동대문구', value: '동대문구', key:1 },
  { label: '동작구', value: '동작구', key:1 },
  { label: '마포구', value: '마포구', key:1 },
  { label: '서대문구', value: '서대문구', key:1 },
  { label: '서초구', value: '서초구', key:1 },
  { label: '성동구', value: '성동구', key:1 },
  { label: '성북구', value: '성북구', key:1 },
  { label: '송파구', value: '송파구', key:1 },
  { label: '양천구', value: '양천구', key:1 },
  { label: '영등포구', value: '영등포구', key:1 },
  { label: '용산구', value: '용산구', key:1 },
  { label: '은평구', value: '은평구', key:1 },
  { label: '종로구', value: '종로구', key:1 },
  { label: '중구', value: '중구', key:1 },
  { label: '중랑구', value: '중랑구', key:1 },
  { label: '계양구', value: '계양구', key:2 },
  { label: '남구', value: '남구', key:2 },
  { label: '남동구', value: '남동구', key:2 },
  { label: '동구', value: '동구', key:2 },
  { label: '부평구', value: '부평구', key:2 },
  { label: '서구', value: '서구', key:2 },
  { label: '연수구', value: '연수구', key:2 },
  { label: '중구', value: '중구', key:2 },
  { label: '강화군', value: '강화군', key:2 },
  { label: '옹진군', value: '옹진군', key:2 },
  { label: '대덕구', value: '대덕구', key:3 },
  { label: '동구', value: '동구', key:3 },
  { label: '서구', value: '서구', key:3 },
  { label: '유성구', value: '유성구', key:3 },
  { label: '중구', value: '중구', key:3 },
  { label: '광산구', value: '광산구', key:4 },
  { label: '남구', value: '남구', key:4 },
  { label: '동구', value: '동구', key:4 },
  { label: '북구', value: '북구', key:4 },
  { label: '서구', value: '서구', key:4 },
  { label: '남구', value: '남구', key:5 },
  { label: '달서구', value: '달서구', key:5 },
  { label: '동구', value: '동구', key:5 },
  { label: '북구', value: '북구', key:5 },
  { label: '서구', value: '서구', key:5 },
  { label: '수성구', value: '수성구', key:5 },
  { label: '중구', value: '중구', key:5 },
  { label: '달성군', value: '달성군', key:5 },
  { label: '남구', value: '남구', key:6 },
  { label: '동구', value: '동구', key:6 },
  { label: '북구', value: '북구', key:6 },
  { label: '중구', value: '중구', key:6 },
  { label: '울주군', value: '울주군', key:6 },
  { label: '강서구', value: '강서구', key:7 },
  { label: '금정구', value: '금정구', key:7 },
  { label: '남구', value: '남구', key:7 },
  { label: '동구', value: '동구', key:7 },
  { label: '동래구', value: '동래구', key:7 },
  { label: '부산진구', value: '부산진구', key:7 },
  { label: '북구', value: '북구', key:7 },
  { label: '사상구', value: '사상구', key:7 },
  { label: '사하구', value: '사하구', key:7 },
  { label: '수영구', value: '수영구', key:7 },
  { label: '연제구', value: '연제구', key:7 },
  { label: '영도구', value: '영도구', key:7 },
  { label: '중구', value: '중구', key:7 },
  { label: '해운대구', value: '해운대구', key:7 },
  { label: '기장군', value: '기장군', key:7 },
  { label: '고양시', value: '고양시', key:8 },
  { label: '과천시', value: '과천시', key:8 },
  { label: '광명시', value: '광명시', key:8 },
  { label: '광주시', value: '광주시', key:8 },
  { label: '구리시', value: '구리시', key:8 },
  { label: '군포시', value: '군포시', key:8 },
  { label: '김포시', value: '김포시', key:8 },
  { label: '남양주시', value: '남양주시', key:8 },
  { label: '동두천시', value: '동두천시', key:8 },
  { label: '부천시', value: '부천시', key:8 },
  { label: '성남시', value: '성남시', key:8 },
  { label: '수원시', value: '수원시', key:8 },
  { label: '시흥시', value: '시흥시', key:8 },
  { label: '안산시', value: '안산시', key:8 },
  { label: '안성시', value: '안성시', key:8 },
  { label: '안양시', value: '안양시', key:8 },
  { label: '양주시', value: '양주시', key:8 },
  { label: '오산시', value: '오산시', key:8 },
  { label: '용인시', value: '용인시', key:8 },
  { label: '의왕시', value: '의왕시', key:8 },
  { label: '의정부시', value: '의정부시', key:8 },
  { label: '이천시', value: '이천시', key:8 },
  { label: '파주시', value: '파주시', key:8 },
  { label: '평택시', value: '평택시', key:8 },
  { label: '포천시', value: '포천시', key:8 },
  { label: '하남시', value: '하남시', key:8 },
  { label: '화성시', value: '화성시', key:8 },
  { label: '가평군', value: '가평군', key:8 },
  { label: '양평군', value: '양평군', key:8 },
  { label: '여주군', value: '여주군', key:8 },
  { label: '연천군', value: '연천군', key:8 },
  { label: '강릉시', value: '강릉시', key:9 },
  { label: '동해시', value: '동해시', key:9 },
  { label: '삼척시', value: '삼척시', key:9 },
  { label: '속초시', value: '속초시', key:9 },
  { label: '원주시', value: '원주시', key:9 },
  { label: '춘천시', value: '춘천시', key:9 },
  { label: '태백시', value: '태백시', key:9 },
  { label: '고성군', value: '고성군', key:9 },
  { label: '양구군', value: '양구군', key:9 },
  { label: '양양군', value: '양양군', key:9 },
  { label: '영월군', value: '영월군', key:9 },
  { label: '인제군', value: '인제군', key:9 },
  { label: '정선군', value: '정선군', key:9 },
  { label: '철원군', value: '철원군', key:9 },
  { label: '평창군', value: '평창군', key:9 },
  { label: '홍천군', value: '홍천군', key:9 },
  { label: '화천군', value: '화천군', key:9 },
  { label: '횡성군', value: '횡성군', key:9 },
  { label: '제천시', value: '제천시', key:10 },
  { label: '청주시', value: '청주시', key:10 },
  { label: '충주시', value: '충주시', key:10 },
  { label: '괴산군', value: '괴산군', key:10 },
  { label: '단양군', value: '단양군', key:10 },
  { label: '보은군', value: '보은군', key:10 },
  { label: '영동군', value: '영동군', key:10 },
  { label: '옥천군', value: '옥천군', key:10 },
  { label: '음성군', value: '음성군', key:10 },
  { label: '증평군', value: '증평군', key:10 },
  { label: '진천군', value: '진천군', key:10 },
  { label: '청원군', value: '청원군', key:10 },
  { label: '계룡시', value: '계룡시', key:11 },
  { label: '공주시', value: '공주시', key:11 },
  { label: '논산시', value: '논산시', key:11 },
  { label: '보령시', value: '보령시', key:11 },
  { label: '서산시', value: '서산시', key:11 },
  { label: '아산시', value: '아산시', key:11 },
  { label: '천안시', value: '천안시', key:11 },
  { label: '금산군', value: '금산군', key:11 },
  { label: '당진군', value: '당진군', key:11 },
  { label: '부여군', value: '부여군', key:11 },
  { label: '서천군', value: '서천군', key:11 },
  { label: '연기군', value: '연기군', key:11 },
  { label: '예산군', value: '예산군', key:11 },
  { label: '청양군', value: '청양군', key:11 },
  { label: '태안군', value: '태안군', key:11 },
  { label: '홍성군', value: '홍성군', key:11 },
  { label: '군산시', value: '군산시', key:12 },
  { label: '김제시', value: '김제시', key:12 },
  { label: '남원시', value: '남원시', key:12 },
  { label: '익산시', value: '익산시', key:12 },
  { label: '전주시', value: '전주시', key:12 },
  { label: '정읍시', value: '정읍시', key:12 },
  { label: '고창군', value: '고창군', key:12 },
  { label: '무주군', value: '무주군', key:12 },
  { label: '부안군', value: '부안군', key:12 },
  { label: '순창군', value: '순창군', key:12 },
  { label: '완주군', value: '완주군', key:12 },
  { label: '임실군', value: '임실군', key:12 },
  { label: '장수군', value: '장수군', key:12 },
  { label: '진안군', value: '진안군', key:12 },
  { label: '광양시', value: '광양시', key:13 },
  { label: '나주시', value: '나주시', key:13 },
  { label: '목포시', value: '목포시', key:13 },
  { label: '순천시', value: '순천시', key:13 },
  { label: '여수시', value: '여수시', key:13 },
  { label: '강진군', value: '강진군', key:13 },
  { label: '고흥군', value: '고흥군', key:13 },
  { label: '곡성군', value: '곡성군', key:13 },
  { label: '구례군', value: '구례군', key:13 },
  { label: '담양군', value: '담양군', key:13 },
  { label: '무안군', value: '무안군', key:13 },
  { label: '보성군', value: '보성군', key:13 },
  { label: '신안군', value: '신안군', key:13 },
  { label: '영광군', value: '영광군', key:13 },
  { label: '영암군', value: '영암군', key:13 },
  { label: '완도군', value: '완도군', key:13 },
  { label: '장성군', value: '장성군', key:13 },
  { label: '장흥군', value: '장흥군', key:13 },
  { label: '진도군', value: '진도군', key:13 },
  { label: '함평군', value: '함평군', key:13 },
  { label: '해남군', value: '해남군', key:13 },
  { label: '화순군', value: '화순군', key:13 },
  { label: '경산시', value: '경산시', key:14 },
  { label: '구미시', value: '구미시', key:14 },
  { label: '김천시', value: '김천시', key:14 },
  { label: '문경시', value: '문경시', key:14 },
  { label: '상주시', value: '상주시', key:14 },
  { label: '안동시', value: '안동시', key:14 },
  { label: '영주시', value: '영주시', key:14 },
  { label: '영천시', value: '영천시', key:14 },
  { label: '포항시', value: '포항시', key:14 },
  { label: '고령군', value: '고령군', key:14 },
  { label: '군위군', value: '군위군', key:14 },
  { label: '봉화군', value: '봉화군', key:14 },
  { label: '성주군', value: '성주군', key:14 },
  { label: '영덕군', value: '영덕군', key:14 },
  { label: '영양군', value: '영양군', key:14 },
  { label: '예천군', value: '예천군', key:14 },
  { label: '울릉군', value: '울릉군', key:14 },
  { label: '울진군', value: '울진군', key:14 },
  { label: '의성군', value: '의성군', key:14 },
  { label: '청도군', value: '청도군', key:14 },
  { label: '청송군', value: '청송군', key:14 },
  { label: '칠곡군', value: '칠곡군', key:14 },
  { label: '거제시', value: '거제시', key:15 },
  { label: '김해시', value: '김해시', key:15 },
  { label: '마산시', value: '마산시', key:15 },
  { label: '밀양시', value: '밀양시', key:15 },
  { label: '양산시', value: '양산시', key:15 },
  { label: '진주시', value: '진주시', key:15 },
  { label: '진해시', value: '진해시', key:15 },
  { label: '창원시', value: '창원시', key:15 },
  { label: '통영시', value: '통영시', key:15 },
  { label: '거창군', value: '거창군', key:15 },
  { label: '고성군', value: '고성군', key:15 },
  { label: '남해군', value: '남해군', key:15 },
  { label: '산청군', value: '산청군', key:15 },
  { label: '의령군', value: '의령군', key:15 },
  { label: '창녕군', value: '창녕군', key:15 },
  { label: '하동군', value: '하동군', key:15 },
  { label: '함안군', value: '함안군', key:15 },
  { label: '함양군', value: '함양군', key:15 },
  { label: '합천군', value: '합천군', key:15 },
  { label: '서귀포시', value: '서귀포시', key:16 },
  { label: '제주시', value: '제주시', key:16 },
  { label: '남제주군', value: '남제주군', key:16 },
  { label: '북제주군', value: '북제주군', key:16 },
];
